// Used to display different summary page for each event type

export const GrowCoachingSummary = () => {
    return (
        <article>
            <strong>GROW Summary</strong>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quis interdum dui. Sed sit amet cursus ex, et hendrerit enim. Fusce blandit blandit justo id mattis. Duis massa magna, placerat id lacus vel, vestibulum ultricies mauris. Morbi molestie magna ut imperdiet sagittis. Duis vestibulum vel neque non accumsan. Vivamus ex nisl, elementum ac ullamcorper efficitur, rutrum efficitur sem. Suspendisse efficitur blandit gravida. Nunc sit amet volutpat urna. Mauris bibendum nibh sapien. Donec imperdiet, erat a hendrerit scelerisque, mauris dui eleifend felis, non laoreet ipsum odio eu odio.</p>
            <p>In neque urna, maximus a pharetra et, feugiat sed leo. Morbi tempor non tellus nec cursus. Sed nec est in leo varius pulvinar at vel ipsum. Quisque varius ultricies auctor. Duis non erat ut nisl aliquam aliquam. Vivamus auctor sed massa nec consectetur. Nam at rhoncus nulla. Nunc maximus, odio eget blandit mollis, ipsum ipsum sodales dolor, a volutpat nibh metus sed leo. Nulla eget consectetur nibh. Praesent porttitor ex ac diam ornare, id mattis eros gravida. Vestibulum libero nulla, dictum a malesuada id, porta quis nisi. Aliquam id orci nisi. Vivamus non elit porttitor, porttitor sapien eget, maximus diam.</p>
            <p>Aliquam suscipit interdum mauris ut dignissim. Pellentesque est nibh, blandit sed volutpat ut, volutpat ut dolor. In mollis scelerisque justo, nec auctor augue facilisis a. Aenean eget quam auctor, varius diam et, ultrices mi. Morbi nec ornare ipsum, ac porttitor ante. Etiam non placerat erat. In eleifend augue a augue suscipit, in lobortis dolor imperdiet. Etiam eu posuere est. Duis nunc lectus, blandit dignissim odio quis, interdum auctor sem. Sed volutpat scelerisque purus sit amet faucibus.</p>
            <p>Nullam at facilisis neque, eu iaculis urna. Cras sagittis varius porta. Nunc eu felis erat. Maecenas at mauris non felis luctus gravida nec tristique velit. Nullam blandit nisl sit amet ligula ultricies, quis volutpat nisi pharetra. Donec condimentum venenatis pretium. Etiam et laoreet elit, ac consequat magna. Aenean semper a neque vitae aliquam. In interdum metus at dui facilisis, ac elementum lacus accumsan. Vestibulum a tellus orci. Quisque tristique, est a cursus malesuada, orci lectus laoreet neque, at consequat odio sem vitae turpis.</p>
            <p>Nunc tellus erat, dignissim et libero eu, consectetur fermentum lectus. Nam malesuada erat ac elementum consectetur. Vivamus ut sagittis nunc, vitae pretium augue. Nunc consequat ligula sit amet elit lacinia molestie. Aliquam nibh nisl, venenatis et auctor in, consectetur iaculis dui. Vestibulum vulputate neque ac aliquam rhoncus. Integer erat augue, vehicula nec porttitor pellentesque, pellentesque volutpat orci. In et rutrum ante. Aliquam quis velit id velit commodo laoreet. In a gravida odio. Nulla interdum nunc mi, vel fermentum nibh fringilla eu. Cras eget laoreet velit. Proin non mi accumsan eros porttitor maximus. In hac habitasse platea dictumst.</p>
        </article>
    )
}

export const InsideOutCoachingSummary = () => {
    return (
        <article>
            <strong>IOC Summary</strong>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quis interdum dui. Sed sit amet cursus ex, et hendrerit enim. Fusce blandit blandit justo id mattis. Duis massa magna, placerat id lacus vel, vestibulum ultricies mauris. Morbi molestie magna ut imperdiet sagittis. Duis vestibulum vel neque non accumsan. Vivamus ex nisl, elementum ac ullamcorper efficitur, rutrum efficitur sem. Suspendisse efficitur blandit gravida. Nunc sit amet volutpat urna. Mauris bibendum nibh sapien. Donec imperdiet, erat a hendrerit scelerisque, mauris dui eleifend felis, non laoreet ipsum odio eu odio.</p>
            <p>In neque urna, maximus a pharetra et, feugiat sed leo. Morbi tempor non tellus nec cursus. Sed nec est in leo varius pulvinar at vel ipsum. Quisque varius ultricies auctor. Duis non erat ut nisl aliquam aliquam. Vivamus auctor sed massa nec consectetur. Nam at rhoncus nulla. Nunc maximus, odio eget blandit mollis, ipsum ipsum sodales dolor, a volutpat nibh metus sed leo. Nulla eget consectetur nibh. Praesent porttitor ex ac diam ornare, id mattis eros gravida. Vestibulum libero nulla, dictum a malesuada id, porta quis nisi. Aliquam id orci nisi. Vivamus non elit porttitor, porttitor sapien eget, maximus diam.</p>
            <p>Aliquam suscipit interdum mauris ut dignissim. Pellentesque est nibh, blandit sed volutpat ut, volutpat ut dolor. In mollis scelerisque justo, nec auctor augue facilisis a. Aenean eget quam auctor, varius diam et, ultrices mi. Morbi nec ornare ipsum, ac porttitor ante. Etiam non placerat erat. In eleifend augue a augue suscipit, in lobortis dolor imperdiet. Etiam eu posuere est. Duis nunc lectus, blandit dignissim odio quis, interdum auctor sem. Sed volutpat scelerisque purus sit amet faucibus.</p>
            <p>Nullam at facilisis neque, eu iaculis urna. Cras sagittis varius porta. Nunc eu felis erat. Maecenas at mauris non felis luctus gravida nec tristique velit. Nullam blandit nisl sit amet ligula ultricies, quis volutpat nisi pharetra. Donec condimentum venenatis pretium. Etiam et laoreet elit, ac consequat magna. Aenean semper a neque vitae aliquam. In interdum metus at dui facilisis, ac elementum lacus accumsan. Vestibulum a tellus orci. Quisque tristique, est a cursus malesuada, orci lectus laoreet neque, at consequat odio sem vitae turpis.</p>
            <p>Nunc tellus erat, dignissim et libero eu, consectetur fermentum lectus. Nam malesuada erat ac elementum consectetur. Vivamus ut sagittis nunc, vitae pretium augue. Nunc consequat ligula sit amet elit lacinia molestie. Aliquam nibh nisl, venenatis et auctor in, consectetur iaculis dui. Vestibulum vulputate neque ac aliquam rhoncus. Integer erat augue, vehicula nec porttitor pellentesque, pellentesque volutpat orci. In et rutrum ante. Aliquam quis velit id velit commodo laoreet. In a gravida odio. Nulla interdum nunc mi, vel fermentum nibh fringilla eu. Cras eget laoreet velit. Proin non mi accumsan eros porttitor maximus. In hac habitasse platea dictumst.</p>
        </article>
    )
}

export const BreakthroughSummary = () => {
    return (
        <article>
            <strong>Breakthroughs Summary</strong>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quis interdum dui. Sed sit amet cursus ex, et hendrerit enim. Fusce blandit blandit justo id mattis. Duis massa magna, placerat id lacus vel, vestibulum ultricies mauris. Morbi molestie magna ut imperdiet sagittis. Duis vestibulum vel neque non accumsan. Vivamus ex nisl, elementum ac ullamcorper efficitur, rutrum efficitur sem. Suspendisse efficitur blandit gravida. Nunc sit amet volutpat urna. Mauris bibendum nibh sapien. Donec imperdiet, erat a hendrerit scelerisque, mauris dui eleifend felis, non laoreet ipsum odio eu odio.</p>
            <p>In neque urna, maximus a pharetra et, feugiat sed leo. Morbi tempor non tellus nec cursus. Sed nec est in leo varius pulvinar at vel ipsum. Quisque varius ultricies auctor. Duis non erat ut nisl aliquam aliquam. Vivamus auctor sed massa nec consectetur. Nam at rhoncus nulla. Nunc maximus, odio eget blandit mollis, ipsum ipsum sodales dolor, a volutpat nibh metus sed leo. Nulla eget consectetur nibh. Praesent porttitor ex ac diam ornare, id mattis eros gravida. Vestibulum libero nulla, dictum a malesuada id, porta quis nisi. Aliquam id orci nisi. Vivamus non elit porttitor, porttitor sapien eget, maximus diam.</p>
            <p>Aliquam suscipit interdum mauris ut dignissim. Pellentesque est nibh, blandit sed volutpat ut, volutpat ut dolor. In mollis scelerisque justo, nec auctor augue facilisis a. Aenean eget quam auctor, varius diam et, ultrices mi. Morbi nec ornare ipsum, ac porttitor ante. Etiam non placerat erat. In eleifend augue a augue suscipit, in lobortis dolor imperdiet. Etiam eu posuere est. Duis nunc lectus, blandit dignissim odio quis, interdum auctor sem. Sed volutpat scelerisque purus sit amet faucibus.</p>
            <p>Nullam at facilisis neque, eu iaculis urna. Cras sagittis varius porta. Nunc eu felis erat. Maecenas at mauris non felis luctus gravida nec tristique velit. Nullam blandit nisl sit amet ligula ultricies, quis volutpat nisi pharetra. Donec condimentum venenatis pretium. Etiam et laoreet elit, ac consequat magna. Aenean semper a neque vitae aliquam. In interdum metus at dui facilisis, ac elementum lacus accumsan. Vestibulum a tellus orci. Quisque tristique, est a cursus malesuada, orci lectus laoreet neque, at consequat odio sem vitae turpis.</p>
            <p>Nunc tellus erat, dignissim et libero eu, consectetur fermentum lectus. Nam malesuada erat ac elementum consectetur. Vivamus ut sagittis nunc, vitae pretium augue. Nunc consequat ligula sit amet elit lacinia molestie. Aliquam nibh nisl, venenatis et auctor in, consectetur iaculis dui. Vestibulum vulputate neque ac aliquam rhoncus. Integer erat augue, vehicula nec porttitor pellentesque, pellentesque volutpat orci. In et rutrum ante. Aliquam quis velit id velit commodo laoreet. In a gravida odio. Nulla interdum nunc mi, vel fermentum nibh fringilla eu. Cras eget laoreet velit. Proin non mi accumsan eros porttitor maximus. In hac habitasse platea dictumst.</p>
        </article>
    )
}
